/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.GUI.ClockFrame;
import org.junit.jupiter.api.Test;

import java.awt.*;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() throws FontFormatException, IOException {
        org.junit.jupiter.api.Assumptions.assumeFalse(GraphicsEnvironment.isHeadless(),
                "Skipping GUI test in headless environment");
        // App classUnderTest = new App();
        ClockFrame clock = new ClockFrame();
        assertNotNull(clock, "app should have a greeting");
    }
}
